# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_ent',
            name='img_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad_ent',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad_outdoor',
            name='img_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad_outdoor',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad_video',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad_video',
            name='video_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
